/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JapanLifeRouteImport } from './routes/japan-life'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CirclesRouteImport } from './routes/circles'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUsernameRouteImport } from './routes/users_.$username'
import { Route as JapanLifeGuideHandleRouteImport } from './routes/japan-life_.$guideHandle'
import { Route as EventsNewRouteImport } from './routes/events_.new'
import { Route as EventsEventHandleRouteImport } from './routes/events_.$eventHandle'
import { Route as DiscountsNewRouteImport } from './routes/discounts_.new'
import { Route as DiscountsDealHandleRouteImport } from './routes/discounts_.$dealHandle'
import { Route as DealsDealHandleRouteImport } from './routes/deals_.$dealHandle'
import { Route as CirclesNewRouteImport } from './routes/circles_.new'
import { Route as CirclesCircleHandleRouteImport } from './routes/circles_.$circleHandle'
import { Route as CareersNewRouteImport } from './routes/careers_.new'
import { Route as CareersJobHandleRouteImport } from './routes/careers_.$jobHandle'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JapanLifeRoute = JapanLifeRouteImport.update({
  id: '/japan-life',
  path: '/japan-life',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesRoute = CirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameRoute = UsersUsernameRouteImport.update({
  id: '/users_/$username',
  path: '/users/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const JapanLifeGuideHandleRoute = JapanLifeGuideHandleRouteImport.update({
  id: '/japan-life_/$guideHandle',
  path: '/japan-life/$guideHandle',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events_/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventHandleRoute = EventsEventHandleRouteImport.update({
  id: '/events_/$eventHandle',
  path: '/events/$eventHandle',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsNewRoute = DiscountsNewRouteImport.update({
  id: '/discounts_/new',
  path: '/discounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsDealHandleRoute = DiscountsDealHandleRouteImport.update({
  id: '/discounts_/$dealHandle',
  path: '/discounts/$dealHandle',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealHandleRoute = DealsDealHandleRouteImport.update({
  id: '/deals_/$dealHandle',
  path: '/deals/$dealHandle',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesNewRoute = CirclesNewRouteImport.update({
  id: '/circles_/new',
  path: '/circles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesCircleHandleRoute = CirclesCircleHandleRouteImport.update({
  id: '/circles_/$circleHandle',
  path: '/circles/$circleHandle',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersNewRoute = CareersNewRouteImport.update({
  id: '/careers_/new',
  path: '/careers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersJobHandleRoute = CareersJobHandleRouteImport.update({
  id: '/careers_/$jobHandle',
  path: '/careers/$jobHandle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/circles': typeof CirclesRoute
  '/deals': typeof DealsRoute
  '/discounts': typeof DiscountsRoute
  '/events': typeof EventsRoute
  '/features': typeof FeaturesRoute
  '/japan-life': typeof JapanLifeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/careers/$jobHandle': typeof CareersJobHandleRoute
  '/careers/new': typeof CareersNewRoute
  '/circles/$circleHandle': typeof CirclesCircleHandleRoute
  '/circles/new': typeof CirclesNewRoute
  '/deals/$dealHandle': typeof DealsDealHandleRoute
  '/discounts/$dealHandle': typeof DiscountsDealHandleRoute
  '/discounts/new': typeof DiscountsNewRoute
  '/events/$eventHandle': typeof EventsEventHandleRoute
  '/events/new': typeof EventsNewRoute
  '/japan-life/$guideHandle': typeof JapanLifeGuideHandleRoute
  '/users/$username': typeof UsersUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/circles': typeof CirclesRoute
  '/deals': typeof DealsRoute
  '/discounts': typeof DiscountsRoute
  '/events': typeof EventsRoute
  '/features': typeof FeaturesRoute
  '/japan-life': typeof JapanLifeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/careers/$jobHandle': typeof CareersJobHandleRoute
  '/careers/new': typeof CareersNewRoute
  '/circles/$circleHandle': typeof CirclesCircleHandleRoute
  '/circles/new': typeof CirclesNewRoute
  '/deals/$dealHandle': typeof DealsDealHandleRoute
  '/discounts/$dealHandle': typeof DiscountsDealHandleRoute
  '/discounts/new': typeof DiscountsNewRoute
  '/events/$eventHandle': typeof EventsEventHandleRoute
  '/events/new': typeof EventsNewRoute
  '/japan-life/$guideHandle': typeof JapanLifeGuideHandleRoute
  '/users/$username': typeof UsersUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/circles': typeof CirclesRoute
  '/deals': typeof DealsRoute
  '/discounts': typeof DiscountsRoute
  '/events': typeof EventsRoute
  '/features': typeof FeaturesRoute
  '/japan-life': typeof JapanLifeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/careers_/$jobHandle': typeof CareersJobHandleRoute
  '/careers_/new': typeof CareersNewRoute
  '/circles_/$circleHandle': typeof CirclesCircleHandleRoute
  '/circles_/new': typeof CirclesNewRoute
  '/deals_/$dealHandle': typeof DealsDealHandleRoute
  '/discounts_/$dealHandle': typeof DiscountsDealHandleRoute
  '/discounts_/new': typeof DiscountsNewRoute
  '/events_/$eventHandle': typeof EventsEventHandleRoute
  '/events_/new': typeof EventsNewRoute
  '/japan-life_/$guideHandle': typeof JapanLifeGuideHandleRoute
  '/users_/$username': typeof UsersUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/careers'
    | '/circles'
    | '/deals'
    | '/discounts'
    | '/events'
    | '/features'
    | '/japan-life'
    | '/login'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/careers/$jobHandle'
    | '/careers/new'
    | '/circles/$circleHandle'
    | '/circles/new'
    | '/deals/$dealHandle'
    | '/discounts/$dealHandle'
    | '/discounts/new'
    | '/events/$eventHandle'
    | '/events/new'
    | '/japan-life/$guideHandle'
    | '/users/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/careers'
    | '/circles'
    | '/deals'
    | '/discounts'
    | '/events'
    | '/features'
    | '/japan-life'
    | '/login'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/careers/$jobHandle'
    | '/careers/new'
    | '/circles/$circleHandle'
    | '/circles/new'
    | '/deals/$dealHandle'
    | '/discounts/$dealHandle'
    | '/discounts/new'
    | '/events/$eventHandle'
    | '/events/new'
    | '/japan-life/$guideHandle'
    | '/users/$username'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/careers'
    | '/circles'
    | '/deals'
    | '/discounts'
    | '/events'
    | '/features'
    | '/japan-life'
    | '/login'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/careers_/$jobHandle'
    | '/careers_/new'
    | '/circles_/$circleHandle'
    | '/circles_/new'
    | '/deals_/$dealHandle'
    | '/discounts_/$dealHandle'
    | '/discounts_/new'
    | '/events_/$eventHandle'
    | '/events_/new'
    | '/japan-life_/$guideHandle'
    | '/users_/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CareersRoute: typeof CareersRoute
  CirclesRoute: typeof CirclesRoute
  DealsRoute: typeof DealsRoute
  DiscountsRoute: typeof DiscountsRoute
  EventsRoute: typeof EventsRoute
  FeaturesRoute: typeof FeaturesRoute
  JapanLifeRoute: typeof JapanLifeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  CareersJobHandleRoute: typeof CareersJobHandleRoute
  CareersNewRoute: typeof CareersNewRoute
  CirclesCircleHandleRoute: typeof CirclesCircleHandleRoute
  CirclesNewRoute: typeof CirclesNewRoute
  DealsDealHandleRoute: typeof DealsDealHandleRoute
  DiscountsDealHandleRoute: typeof DiscountsDealHandleRoute
  DiscountsNewRoute: typeof DiscountsNewRoute
  EventsEventHandleRoute: typeof EventsEventHandleRoute
  EventsNewRoute: typeof EventsNewRoute
  JapanLifeGuideHandleRoute: typeof JapanLifeGuideHandleRoute
  UsersUsernameRoute: typeof UsersUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/japan-life': {
      id: '/japan-life'
      path: '/japan-life'
      fullPath: '/japan-life'
      preLoaderRoute: typeof JapanLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles': {
      id: '/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof CirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/$username': {
      id: '/users_/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof UsersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/japan-life_/$guideHandle': {
      id: '/japan-life_/$guideHandle'
      path: '/japan-life/$guideHandle'
      fullPath: '/japan-life/$guideHandle'
      preLoaderRoute: typeof JapanLifeGuideHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/new': {
      id: '/events_/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$eventHandle': {
      id: '/events_/$eventHandle'
      path: '/events/$eventHandle'
      fullPath: '/events/$eventHandle'
      preLoaderRoute: typeof EventsEventHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts_/new': {
      id: '/discounts_/new'
      path: '/discounts/new'
      fullPath: '/discounts/new'
      preLoaderRoute: typeof DiscountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts_/$dealHandle': {
      id: '/discounts_/$dealHandle'
      path: '/discounts/$dealHandle'
      fullPath: '/discounts/$dealHandle'
      preLoaderRoute: typeof DiscountsDealHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals_/$dealHandle': {
      id: '/deals_/$dealHandle'
      path: '/deals/$dealHandle'
      fullPath: '/deals/$dealHandle'
      preLoaderRoute: typeof DealsDealHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles_/new': {
      id: '/circles_/new'
      path: '/circles/new'
      fullPath: '/circles/new'
      preLoaderRoute: typeof CirclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles_/$circleHandle': {
      id: '/circles_/$circleHandle'
      path: '/circles/$circleHandle'
      fullPath: '/circles/$circleHandle'
      preLoaderRoute: typeof CirclesCircleHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers_/new': {
      id: '/careers_/new'
      path: '/careers/new'
      fullPath: '/careers/new'
      preLoaderRoute: typeof CareersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers_/$jobHandle': {
      id: '/careers_/$jobHandle'
      path: '/careers/$jobHandle'
      fullPath: '/careers/$jobHandle'
      preLoaderRoute: typeof CareersJobHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CareersRoute: CareersRoute,
  CirclesRoute: CirclesRoute,
  DealsRoute: DealsRoute,
  DiscountsRoute: DiscountsRoute,
  EventsRoute: EventsRoute,
  FeaturesRoute: FeaturesRoute,
  JapanLifeRoute: JapanLifeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  CareersJobHandleRoute: CareersJobHandleRoute,
  CareersNewRoute: CareersNewRoute,
  CirclesCircleHandleRoute: CirclesCircleHandleRoute,
  CirclesNewRoute: CirclesNewRoute,
  DealsDealHandleRoute: DealsDealHandleRoute,
  DiscountsDealHandleRoute: DiscountsDealHandleRoute,
  DiscountsNewRoute: DiscountsNewRoute,
  EventsEventHandleRoute: EventsEventHandleRoute,
  EventsNewRoute: EventsNewRoute,
  JapanLifeGuideHandleRoute: JapanLifeGuideHandleRoute,
  UsersUsernameRoute: UsersUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
